Fliplet/fliplet-widget-chart-bar

- js/build.js
Fixes https://github.com/Fliplet/fliplet-studio/issues/1326
> Updates support for arrays in data summary

- js/build.js
- beforeQueryChart
- afterQueryChart
- data_point_interact
- legend_filter
> Hooks + GA

- js/build.js
Changes the default colours to match the new colours in the new theme.
> Updates chart's default colors

- js/build.js
- Adds a Hook handler to reconfigure the Chart after the styles are changes in the Appearance settings
> Styles changed hook

- interface.html
@tonytlwu @squallstar 
Fliplet/fliplet-studio#4911
Added link on "Need help" button.
> Clicking on "Need help" now leads to Fliplet documentation "How to Configure Charts"

- js/build.js
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/5529
Make use of the new hook added in https://github.com/Fliplet/fliplet-api/pull/3793
> Use new appearance hook

- js/build.js
Follows https://github.com/Fliplet/fliplet-widget-chart-bar/pull/21
> Ensures chart instance is made available after render

- js/build.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/5615
> Start autorefresh when initial data fetch fails

- js/build.js
https://github.com/Fliplet/fliplet-studio/issues/5477
Allow users to dynamically change chart colors.
https://share.getcloudapp.com/8LujEbOj
> [Fix] Allow users to dynamically change chart colors. For production.

- js/build.js
https://github.com/Fliplet/fliplet-studio/issues/5477
Allow users to dynamically change chart colors.
https://share.getcloudapp.com/8LujEbOj
> [Fix] Allow users to dynamically change chart colors.

- js/interface.js
OD-16 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-16
Email, SMS verification.
Pass new variable for the default name into DS Provider
https://screencast-o-matic.com/watch/cY63XH7PGu
@upplabs-alex-levchenko @YaroslavOvdii
> OD-16 [Feature] Integration new default variable into Bar Chart

- js/interface.js
OD-218 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-218
Fix to bug with security rules alert
@upplabs-alex-levchenko @YaroslavOvdii
> OD-218 [Fix] Addes acces rules to Chart Bar

- js/interface.js
OD-218 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-218
Fix to bug with security rules alert
@upplabs-alex-levchenko @YaroslavOvdii
> OD-218 [Fix] Added access rules to chart bar

- css/interface.css
- interface.html
OD-187 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-187
Change need help link
@YaroslavOvdii
> OD-187 [Feature] Chnage need help link

- widget.json
Ref. https://weboo.atlassian.net/browse/ID-290
Requires Fliplet/fliplet-studio#7074
> ID-290 [Maintenance] Ensures apps on the new theme don't see settings related to the old theme

- .eslintrc
- .gitignore
- js/build.js
- js/interface.js
- package-lock.json
> [ESLint] Added ESLint for Chart: Bar

- js/build.js
https://weboo.atlassian.net/browse/OD-96
Charts will inherit colors from Highlight color and Secondary color for Color 1 and Color 2
https://share.getcloudapp.com/04uOB8l1
> OD-96 [Feature] Charts will inherit colors from Highlight color and Secondary color for Color 1 and Color 2

- interface.html
- js/build.js
- js/interface.js
Ref. https://weboo.atlassian.net/browse/ID-458
Requires https://github.com/Fliplet/fliplet-api/pull/4384
Adds support for:
```js
Fliplet.Chart.get('My chart').then(function(chart) {
// Refresh chart
chart.refresh();
});
```
> ID-458 [Feat] Adds chart name and support for refreshing via JS API

- build.html
- js/build.js
https://weboo.atlassian.net/browse/OD-96
Updated instance version of the Chart: Bar component to avoid issues with older versions
> OD-96 [Fix] Updated instance version of the Chart: Bar component

- build.html
https://weboo.atlassian.net/browse/OD-270
Fixed instances name
https://share.getcloudapp.com/xQuY9ZXg
> OD-270 [Fix] Users will be able to see Chart: Bar

- js/build.js
@sofiiakvasnevska
OD-246 https://weboo.atlassian.net/browse/OD-246
Check widget id for color change event
https://monosnap.com/file/1rV3LpTomFnI0VI7xNwaH19iOeLajD
@upplabs-alex-levchenko @AndrRyaz @YaroslavOvdii
This fix requires changes in Theme, Charts (Column, Bar, Scatter, Line, Donut)
> OD-246 [Fix] Check widget id for color change event

- build.html
- js/build.js
- translation.json
Ref. https://weboo.atlassian.net/browse/ID-1516
> ID-1516 [Feat] Localize translations, date and number formats
